# Generated by Django 6.1 on 2026-08-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=255)),
                ('isnew', models.BooleanField(default=False)),
                ('isoffer', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
